config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
  resources :notifications
  resources :users
  resources :posts do
    resources :likes
    resources :comments
  end
  get '/users/sign_out'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[ show edit update destroy ]

  # GET /notifications or /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1 or /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications or /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to notification_url(@notification), notice: "Notification was successfully created." }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1 or /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to notification_url(@notification), notice: "Notification was successfully updated." }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1 or /notifications/1.json
  def destroy
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url, notice: "Notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:body, :url, :user_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification) do |form| %>
  <% if notification.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% notification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
<div id="<%= dom_id notification %>">
  <p>
    <strong>Body:</strong>
    <%= notification.body %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= notification.url %>
  </p>

  <p>
    <strong>User:</strong>
    <%= notification.user_id %>
  </p>

</div>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Show this notification", @notification %> |
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notifications</h1>

<div id="notifications">
  <% @notifications.each do |notification| %>
    <%= render notification %>
    <p>
      <%= link_to "Show this notification", notification %>
    </p>
  <% end %>
</div>

<%= link_to "New notification", new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notification %>

<div>
  <%= link_to "Edit this notification", edit_notification_path(@notification) %> |
  <%= link_to "Back to notifications", notifications_path %>

  <%= button_to "Destroy this notification", @notification, method: :delete %>
</div>