config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
  resources :notifications
  resources :users
  resources :posts do
    resources :likes
    resources :comments
  end
  get '/users/sign_out'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include Gravtastic
  gravtastic
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      #user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    after_create_callbacks if @user.new_record? && @user.save

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      flash.alert = "Error: #{@user.errors.full_messages.join}"
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
    @user = User.where(id: params[:id]).first
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.with(user: @user).welcome_email.deliver_later
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :city, :state)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render "form", user: current_user %>

<div>
  <%= link_to "Show this user", user_path(current_user) %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<% @users.each do |user| %>
    <p><%= link_to user.name, user_path(user) %></p>
    <% if user.friends.exclude?(current_user) && user != current_user && current_user.pending_friends.exclude?(user) %>
        <%=button_to 'Send Request', friend_requests_path(user_id: current_user.id, friend_id: user.id), method: :post%>
    <%end%>
<%end%>
<br>
<%= link_to 'Your Profile', user_path(current_user.id)%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<h1>You are user:</h1>
<p>Name: <% if @user.name %>
    <%= @user.name %>
    <% else %>
    <%= "none" %>
    <%end%>
    </p>
<p>Email: <%= @user.email %></p>
<p>City: <% if @user.city %>
    <%= @user.city %>
    <% else %>
    <%= "none" %>
    <%end%>
    </p>
<p>State: <% if @user.state %>
    <%= @user.state %>
    <% else %>
    <%= "none" %>
    <%end%>
    </p>
<br>
<%= image_tag @user.gravatar_url %>
<br>
<%= link_to "Edit your profile", edit_user_path(@user) %>
<%= link_to 'Create post', new_post_path %>
<h2> Posts </h2>
<% current_user.posts.each do |post| %>
    <%= post.body %>
    <br>
<%end%>

<h3> These are my friends</h3>
<% @user.friends.each do |friend| %>
    <%= link_to friend.name, user_path(friend)%>
<%end%>