config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
  resources :notifications
  resources :users
  resources :posts do
    resources :likes
    resources :comments
  end
  get '/users/sign_out'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }
  validate :not_self
  validate :not_friends
  validate :not_pending

  def accept
    user.friends << friend
    destroy
  end

  private

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

  def not_friends
    errors.add(:friend, 'is already added') if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
  end

end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :set_friend_request, except: [:index, :new, :create]

  # GET /friend_requests or /friend_requests.json
  def index
    @incoming = FriendRequest.where(friend: current_user)
    @outgoing = current_user.friend_requests
  end

  # GET /friend_requests/1 or /friend_requests/1.json
  def show
  end

  # GET /friend_requests/new
  def new
    @friend_request = FriendRequest.new
  end

  # GET /friend_requests/1/edit
  def edit
  end

  # POST /friend_requests or /friend_requests.json
  def create
    @friend = User.find(params[:friend_id])
    @friend_request = current_user.friend_requests.new(friend: @friend)

    respond_to do |format|
      if @friend_request.save
        format.html { redirect_to users_path notice: "Friend request was successfully created." }
        format.json { render :show, status: :created, location: @friend_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_requests/1 or /friend_requests/1.json
  def update
    @friend_request.accept
    respond_to do |format|
      format.html { redirect_to users_path, notice: "Friend request was accepted!" }
      format.json { head :no_content }
    end
  end

  # DELETE /friend_requests/1 or /friend_requests/1.json
  def destroy
    @friend_request.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: "Friend request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_request
      @friend_request = FriendRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_request_params
      params.require(:friend_request).permit(:user_id, :friend_id)
    end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_form.html.erb
<%= form_with(model: friend_request) do |form| %>
  <% if friend_request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend_request.errors.count, "error") %> prohibited this friend_request from being saved:</h2>

      <ul>
        <% friend_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.hidden_field :friend_id, value: user.id %>
  </div>

  <div>
    <p>Do you want to send this user a request?</p>
    <%= form.submit %>
  </div>
<% end %>

app/views/friend_requests/_friend_request.html.erb
<div id="<%= dom_id friend_request %>">
  <p>
    <strong>User:</strong>
    <%= friend_request.user_id %>
  </p>

  <p>
    <strong>Friend:</strong>
    <%= friend_request.friend_id %>
  </p>

</div>

app/views/friend_requests/edit.html.erb
<h1>Editing friend request</h1>

<%= render "form", friend_request: @friend_request %>

<br>

<div>
  <%= link_to "Show this friend request", @friend_request %> |
  <%= link_to "Back to friend requests", friend_requests_path %>
</div>

app/views/friend_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friend requests</h1>

<div id="friend_requests">
  <% @incoming.each do |friend_request| %>
    <%= friend_request.user.name %>
    <%= button_to "Accept Request", friend_request_path(friend_request), method: :patch %>
  <% end %>
</div>

app/views/friend_requests/new.html.erb
<h1>New friend request</h1>

<%= render "form", friend_request: @friend_request %>

<br>

<div>
  <%= link_to "Back to friend requests", friend_requests_path %>
</div>

app/views/friend_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend_request %>

<div>
  <%= link_to "Edit this friend request", edit_friend_request_path(@friend_request) %> |
  <%= link_to "Back to friend requests", friend_requests_path %>

  <%= button_to "Destroy this friend request", @friend_request, method: :delete %>
</div>